### PR TITLE
Updated class to cater for foreground (transparent shadow overlay) on bu...

### PR DESCRIPTION
**Pull request by CyberFerret**
Hi, I have edited my copy of the class to allow for a foreground image as well.

My button images actually comprise of 3 layers - the background, the button itself and an overlay over the top to provide a 'shadow' effect.

The changes here work fine when I tested.  They may be useful in the main branch for future users...?

Thanks,
Devan

### CODE REVIEW

**Comment by hollance** [comment]
Cool, I'll take a look at it later. Thanks for the patch!

-Matthijs

On 14-01-12 12:39, CyberFerret wrote:

> Hi, I have edited my copy of the class to allow for a foreground image as well.
> 
> My button images actually comprise of 3 layers - the background, the button itself and an overlay over the top to provide a 'shadow' effect.
> 
> The changes here work fine when I tested.  They may be useful in the main branch for future users...?
> 
> Thanks,
> Devan
> 
> You can merge this Pull Request by running:
> 
>    git pull https://github.com/CyberFerret/MHRotaryKnob patch-1
> 
> Or you can view, comment on it, or merge it online at:
> 
>    https://github.com/hollance/MHRotaryKnob/pull/1
> 
> -- Commit Summary --
> - Updated class to cater for foreground (transparent shadow overlay) on button.
> 
> -- File Changes --
> 
> M Classes/MHRotaryKnob.h (4)
> 
> -- Patch Links --
> 
>    https://github.com/hollance/MHRotaryKnob/pull/1.patch
>    https://github.com/hollance/MHRotaryKnob/pull/1.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/hollance/MHRotaryKnob/pull/1

## 

Hollance: iPad + iPhone App Development
Nijverheidssingel 119
4811ZV Breda
The Netherlands
KvK Number: 51067153
VAT Number: NL155479489B02
http://www.hollance.com

**Comment by hollance** [comment]
Can you give me an example of why such a foreground image view is necessary? Perhaps with an image to illustrate it...

**Comment by CyberFerret** [comment]
The particular knob images I am using on my project comprise of 3 layers to get that '3d' look to them.  Refer the linked image:  http://farm8.staticflickr.com/7147/6697914381_2f62d5374c.jpg

The final knob (on the left) is comprised of the adjacent (1) Background shadow (2) Actual rotatable knob and (3) foreground shadow.

The foreground shadow being on top means that when the red indicator on the rotating knob descends into the lower region  whilst rotating, it gradually gets darker, adding to that whole 3d effect.

There is probably a better way to do this, but I am not a 3d graphics programmer! :)

**Comment by hollance** [comment]
OK, I see what you mean. I'm reluctant to allow for too many customization options in this class, but this one seems reasonable. Thanks again!

**Pull request closed without merging**
